// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/recruit/Activities.tsx": () => import("../components/mockups/recruit/Activities.tsx"),
  "./components/mockups/recruit/Candidates.tsx": () => import("../components/mockups/recruit/Candidates.tsx"),
  "./components/mockups/recruit/ChangeOrders.tsx": () => import("../components/mockups/recruit/ChangeOrders.tsx"),
  "./components/mockups/recruit/Clients.tsx": () => import("../components/mockups/recruit/Clients.tsx"),
  "./components/mockups/recruit/Companies.tsx": () => import("../components/mockups/recruit/Companies.tsx"),
  "./components/mockups/recruit/Contacts.tsx": () => import("../components/mockups/recruit/Contacts.tsx"),
  "./components/mockups/recruit/Dashboard.tsx": () => import("../components/mockups/recruit/Dashboard.tsx"),
  "./components/mockups/recruit/Documents.tsx": () => import("../components/mockups/recruit/Documents.tsx"),
  "./components/mockups/recruit/Financials.tsx": () => import("../components/mockups/recruit/Financials.tsx"),
  "./components/mockups/recruit/Forecasting.tsx": () => import("../components/mockups/recruit/Forecasting.tsx"),
  "./components/mockups/recruit/Integrations.tsx": () => import("../components/mockups/recruit/Integrations.tsx"),
  "./components/mockups/recruit/Jobs.tsx": () => import("../components/mockups/recruit/Jobs.tsx"),
  "./components/mockups/recruit/Onboarding.tsx": () => import("../components/mockups/recruit/Onboarding.tsx"),
  "./components/mockups/recruit/PhasesGates.tsx": () => import("../components/mockups/recruit/PhasesGates.tsx"),
  "./components/mockups/recruit/Pipeline.tsx": () => import("../components/mockups/recruit/Pipeline.tsx"),
  "./components/mockups/recruit/Placements.tsx": () => import("../components/mockups/recruit/Placements.tsx"),
  "./components/mockups/recruit/Planning.tsx": () => import("../components/mockups/recruit/Planning.tsx"),
  "./components/mockups/recruit/Projects.tsx": () => import("../components/mockups/recruit/Projects.tsx"),
  "./components/mockups/recruit/Resources.tsx": () => import("../components/mockups/recruit/Resources.tsx"),
  "./components/mockups/recruit/SOWs.tsx": () => import("../components/mockups/recruit/SOWs.tsx")
};
